#
# Copyright (C) 2023 Xiaomi Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

include $(APPDIR)/Make.defs

CXXEXT = .cpp

CXXSRCS += Errors.cpp
CXXSRCS += FileMap.cpp
CXXSRCS += JenkinsHash.cpp
CXXSRCS += LightRefBase.cpp
CXXSRCS += Looper.cpp
CXXSRCS += misc.cpp
CXXSRCS += NativeHandle.cpp
CXXSRCS += Printer.cpp
CXXSRCS += RefBase.cpp
CXXSRCS += SharedBuffer.cpp
CXXSRCS += StopWatch.cpp
CXXSRCS += String8.cpp
CXXSRCS += String16.cpp
CXXSRCS += StrongPointer.cpp
CXXSRCS += SystemClock.cpp
CXXSRCS += Threads.cpp
CXXSRCS += Timers.cpp
CXXSRCS += Tokenizer.cpp
CXXSRCS += Unicode.cpp
CXXSRCS += VectorImpl.cpp

include $(APPDIR)/Application.mk
